### ISSUE TITLE
not able to create resource in webapp

### ISSUE THREAD

**Issue by shrimpy** [NuGet/NuGet.Protocol#12]
when try to create resource as below from repo:

```
sourceRepo.GetResourceAsync<DownloadResource>()
``` 

code will die there (thread seems to be dead)

**Comment by shrimpy** [comment]
i think i found the issue, in [V2PackageRepositoryResourceProvider.cs, line 48](https://github.com/NuGet/NuGet.Protocol/blob/master/src/NuGet.Client.V2/V2PackageRepositoryResourceProvider.cs#L48), there is a ".Result" blocking the thread, however underneath the code path, there are multiple async-await which cause deadlock for webapp.

why not make the whole code path async-await?

**Comment by shrimpy** [comment]
two new issue:

1) Not able to create v3 resource object
when create a v3 resource object, will be dead lock in [DataClient.cs](https://github.com/NuGet/NuGet.Protocol/blob/master/src/DataClient/DataClient.cs#L84)

2) when there is nested async-away, not able to create v2 resource object
see sample method from [here, deadline will happen on line 29](https://gist.github.com/shrimpy/85f998350caaf7ee045f)

**Comment by emgarten** [comment]
This is fixed in NuGet.Protocol.V2V3 3.0.0-pre-20150129084044 

The code paths now use Async by default end to end as suggested. Waits will only occur when calling the non-async methods at the top level of the API.
