### ISSUE TITLE
V3 DownloadResource.GetStream does not support seek operations.

### ISSUE THREAD

**Issue by shrimpy** [NuGet/NuGet.Protocol#15]
this cause issue when we try to pipe a stream into another stream. we will have to read the whole buffer into memory

**Comment by emgarten** [comment]
DownloadResource returns the stream from the httpclient, for most NuGet scenarios it will be much less efficient for the protocol to read the stream into memory inorder to return a seekable stream since we usually write it straight to disk. We'll evaluate this one after 3.0.0-beta

**Comment by emgarten** [comment]
The V3 download resource would need to also copy the stream to a memory stream to make this work. It would be more consistent if it were always a memory stream, but much less efficient for callers wanting to download straight to disk.
