### ISSUE TITLE
ArgumentNullException when try to get any resource when running against V3 Feed

### ISSUE THREAD

**Issue by shrimpy** [NuGet/NuGet.Protocol#17]
Parameter name: baseUrl","ExceptionType":"System.ArgumentNullException","StackTrace":"   at NuGet.Client.V3RegistrationResource..ctor(HttpClient client, Uri baseUrl)
   at NuGet.Client.V3RegistrationResourceProvider.<TryCreate>d__0.MoveNext()

**Comment by emgarten** [comment]
The service index needs an unversioned @type to support older packages

**Comment by sblom** [comment]
The service index with unversioned endpoints has been restored. We'd love to coordinate with you an opportunity to change your usage to a versioned one.
