### ISSUE TITLE
list only packages that are compatible

### ISSUE THREAD

**Issue by bitbonk** [NuGet/NuGet.Protocol#22]
It would be cool to have an API that lets me list only those packages that are compatible with the framework version of my current project. So for example if my current project targets .NET 2.0 and a package only has content for .NET 4.0 (*\net40* is present but *\net20* is not) it should not be listed in the first place.

As a bonus it would be great that if an earlier version of this package exists that *does* support my current target framework it should be possible to list it instead.

As the amount of packages grows, it becomes harder and harder to find to right package, especially when working with legacy code.

This is a similar issue: http://stackoverflow.com/questions/22568725/is-there-a-way-to-specify-net-framework-version-argument-while-using-install-pa

**Comment by lukas-ais** [comment]
+1

**Comment by emgarten** [comment]
There has been some work done to support target framework filtering in search. Take a look at the SearchFilter class which takes framework names.

**Comment by emgarten** [comment]
Filed NuGet/Home#318 for this. We will soon be disabling issues from this repository and all issues need to be filed at https://github.com/NuGet/Home/issues
