### ISSUE TITLE
PowerShell/OneGet search resource

### ISSUE THREAD

**Issue by darek-msft** [NuGet/NuGet.Protocol#27]
We're currently using UISearchResource, but need more options for OneGet and PsGet:

Query
   - SearchFilter should include PackageType (e.g. PowerShell)
   - [stretch] minimum, maximum, required version

Results
   - Custom metadata (especially PowerShell)
   - Copyright, Language, Release Notes

**Comment by emgarten** [comment]
Filed NuGet/Home#317 for this. We will soon be disabling issues from this repository and all issues need to be filed at https://github.com/NuGet/Home/issues
