### ISSUE TITLE
LatestPackageMetadata from UISearchMetadata  is always null when perform UISearchResource.Search

### ISSUE THREAD

**Issue by shrimpy** [NuGet/NuGet.Protocol#9]

**Comment by emgarten** [comment]
This hasn't been hooked up since the search server is missing a few fields needed for the UIMetadata, but this should be fixed in the client code to start using it anyways.

**Comment by shrimpy** [comment]
we can but will be very bad performence. e.g search result has 500 package. i will need to send request per package to get their UIPackageMetadata. i don`t think we (who consume the dll) should do that

**Comment by emgarten** [comment]
This is fixed in NuGet.Protocol.V2V3 3.0.0-pre-20150129084044 
LatestPackageMetadata now contains the package info for the latest version.
